services:
  - type: web
    name: adultsite-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt && python manage.py migrate && python manage.py create_superuser_if_needed && python manage.py collectstatic --noinput
    startCommand: gunicorn adultsite.wsgi --bind 0.0.0.0:$PORT --workers 3 --timeout 120
