from django.urls import path
from . import api_views

urlpatterns = [
    path('content/', api_views.content_list, name='api_content_list'),
    path('content/<int:pk>/', api_views.content_detail, name='api_content_detail'),
    path('creators/', api_views.creators_list, name='api_creators_list'),
    path('creators/me/', api_views.creator_self, name='api_creator_self'),
    path('creators/<int:pk>/', api_views.creator_detail, name='api_creator_detail'),
    path('creators/<int:pk>/follow/', api_views.follow_creator, name='api_creator_follow'),
    path('creators/<int:pk>/subscribe/', api_views.subscribe_creator, name='api_creator_subscribe'),
    path('auth/register/', api_views.register_user, name='api_register'),
    path('auth/login/', api_views.login_user, name='api_login'),
    path('auth/logout/', api_views.logout_user, name='api_logout'),
    path('auth/user/', api_views.current_user, name='api_current_user'),
    path('auth/settings/', api_views.update_settings, name='api_update_settings'),
    path('purchase/content/<int:pk>/', api_views.purchase_content, name='api_purchase_content'),
    path('rooms/', api_views.rooms_list, name='api_rooms_list'),
    path('rooms/<int:pk>/', api_views.room_detail, name='api_room_detail'),
    path('rooms/<int:pk>/join/', api_views.join_room, name='api_room_join'),
    path('subscriptions/', api_views.subscriptions_list, name='api_subscriptions_list'),
    path('dating/discover/', api_views.dating_discover, name='api_dating_discover'),
    path('locations/countries/', api_views.locations_countries, name='api_locations_countries'),
    path('locations/states/', api_views.locations_subdivisions, name='api_locations_states'),
    path('terms/', api_views.terms_text, name='api_terms'),
    path('paystack/initialize/<int:pk>/', api_views.paystack_initialize_subscription, name='api_paystack_init'),
    path('paystack/webhook/', api_views.paystack_webhook, name='api_paystack_webhook'),
    path('dating/profile/me/', api_views.current_user, name='api_dating_profile_me'),
    path('dating/profile/<int:pk>/', api_views.dating_profile_detail, name='api_dating_profile_detail'),
    path('dating/profile/update/', api_views.update_dating_profile, name='api_update_dating_profile'),
    path('dating/swipe/', api_views.dating_swipe, name='api_dating_swipe'),
    path('dating/matches/', api_views.dating_matches, name='api_dating_matches'),
    path('chats/', api_views.chat_threads, name='api_chat_threads'),
    path('chats/start/', api_views.start_chat, name='api_chat_start'),
    path('chats/<int:pk>/', api_views.chat_detail, name='api_chat_detail'),
    path('chats/<int:pk>/messages/', api_views.send_message, name='api_chat_send_message'),
    path('notifications/', api_views.notifications_list, name='api_notifications_list'),
    path('notifications/stream/', api_views.notifications_stream, name='api_notifications_stream'),
]
