# Generated by Django 6.0.5 on 2026-05-31 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220)),
                ('description', models.TextField(blank=True)),
                ('content_type', models.CharField(choices=[('video', 'Video'), ('leak', 'Leak'), ('story', 'Story')], default='video', max_length=16)),
                ('publish_date', models.DateTimeField(auto_now_add=True)),
                ('is_published', models.BooleanField(default=True)),
                ('age_restricted', models.BooleanField(default=True)),
                ('video_file', models.FileField(blank=True, null=True, upload_to='videos/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='thumbnails/')),
                ('story_text', models.TextField(blank=True)),
                ('source_url', models.URLField(blank=True)),
            ],
            options={
                'ordering': ['-publish_date'],
            },
        ),
    ]
