# Generated by Django 6.0.5 on 2026-06-02 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_app', '0004_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentitem',
            name='show_on_home',
            field=models.BooleanField(default=True),
        ),
    ]
